spring:
  application:
    name: config-consumer

  profiles:
    active: dev

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      label: latest

  config:
    import: configserver:http://localhost:8887
